
//
// Created by Felix Bridault on 15/11/2018.
//

#ifndef GRASSLANDS_PASSMASK_H
#define GRASSLANDS_PASSMASK_H

#define PASS_ALL ~0
#define PASS_DEFAULT 1
#define PASS_SHADOW 2
#define PASS_DEPTH_NON_TRANSMISIVE 4
#define PASS_DEPTH_TRANSMISIVE 8

#endif //GRASSLANDS_PASSMASK_H
